name: '😇 疑问或帮助 Help Wanted'
description: '疑问或需要帮助 | Need help'
title: '[Question] '
labels: '😇 Help Wanted'
body:
  - type: markdown
    attributes:
      value: |
        - 反馈一个问题缺陷, 请确保你已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467)
        - Report an bug, please make sure you have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
  - type: checkboxes
    attributes:
      label: '👀 检查清单 | Initial checklist'
      options:
        - label: 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
          required: true
        - label: 我已经搜索了 [issues](https://github.com/lobehub/sd-webui-lobe-theme/issues) 和 [discussions](https://github.com/lobehub/sd-webui-lobe-theme/discussions) 但无法找到帮助 | I searched [issues](https://github.com/lobehub/sd-webui-lobe-theme/issues) and [discussions](https://github.com/lobehub/sd-webui-lobe-theme/discussions) and couldn’t find anything (or linked relevant results below)
          required: true
  - type: textarea
    attributes:
      label: '🧐 问题描述 | Proposed Solution'
      description: |
        清晰且简洁地描述你遇到的问题。请按照以下的故障排除步骤操作，更新 webui 和 lobe 主题到最新版本。如果问题仍然存在，尝试检查是否有其他插件与之冲突，并提供冲突插件的名称。
        A clear and concise description of what your problem. Please follow the troubleshooting steps below, update the webui and lobe theme to the latest version. If the problem persists, try to check if there is a conflict with other plugins and provide the name of the conflicting plugin.
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📝 补充信息 | Additional Information'
      description: Add any other context about the problem here.
